FROM ubuntu:16.04

RUN apt-get -y update \
    && apt-get -y install apache2 \
    && echo "Hello from Docker Site!" > /var/www/html/index.html

CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
EXPOSE 80
	
