FROM ubuntu

RUN apt update -y \
    && apt-get install apache2 \
    && echo "Hello from Docker Site!" > /var/www/html/index.html

CMD systemctl enable apache2 \
    && systemctl start apache2
EXPOSE 80
	
