apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
        listen  80 ;
        
        location / {
            root /opt/www;
            index index.html;
        }
    }
