apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv

spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /mnt/nfs_k8s
    server: 34.123.128.123
